package marinov.hristo.task5.main;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * @author HristoMarinov (christo_marinov@abv.bg).
 */
public class DummyData {

    // Dummy data
    List<String> productNames = new ArrayList<>(
            Arrays.asList(
                    "Welch's Fruit Snacks Mixed Fruit",
                    "Kellogg's Rice Krispies Treats Crispy Marshmallow Squares",
                    "Cheez-It Original/White Cheddar/Cheddar Jack Baked",
                    "Kellogg's Rice Krispies Treats Crispy Marshmallow Square ",
                    "Nabisco Original Premium Saltine Crackers",
                    "Betty Crocker® Fruit by the Foot®/Fruit Roll-Ups®",
                    "Nabisco Chips Ahoy! Original Chocolate Chip Cookies, 13 oz",
                    "Slim Jim Original Smoked Snack Sticks, 0.28 oz, 26 ct",
                    "Austin® Variety Pack™ Crackers 8-1.38 oz.",
                    "Snack Pack Vanilla/Chocolate Pudding Cups, 3.25 oz, 12 count",
                    "Lays Classic Mix 20 pk, 20 oz",
                    "Mott's® Medleys Assorted Fruit Flavored Snacks 24-0.8 oz. Pouches",
                    "Nabisco Ritz Crackers, 20.6 oz",
                    "Planters Honey Roasted Peanuts, 1 oz, 10 coun",
                    "Quaker Caramel Corn Rice Cakes, 6.56 oz",
                    "Del Monte No Sugar Added Variety Fruit Cups, 12 ct",
                    "Nabisco Oreo Chocolate Sandwich Cookies, 19.1 oz",
                    "Great Value Low Fat Pretzel Tiny Twists, 20 oz",
                    "Pringles Potato Crisps Chips Variety Pack, 27 count, 19.19 oz",
                    "Royal Dansk Danish Butter Cookies, 12 ounce tin",
                    "Quaker Chewy Chocolate Chip Granola Bars, 0.84 oz, 24 count",
                    "Lay's Flavor Mix Variety Pack, 1 oz, 20 count",
                    "UTZ Cheese Balls, 28 oz",
                    "Great Value Chocolate Chunk Chewy Granola Bars Variety Pack, 0.84 oz, 24 ct",
                    "Nutella: Hazelnut With Skim Milk & Cocoa Spread, 26.5 oz",
                    "Nabisco Newtons Fig Cookies, 2 oz, 12 count",
                    "Nutella: Hazelnut With Skim Milk Cocoa Spread, 13 Oz",
                    "Nature Valley® Oats 'n Honey Crunchy Granola Bars 18-2 ct Pouches",
                    "Great Value Vanilla Wafers, 11 oz",
                    "Pop Weaver Extra Butter Microwave Popcorn, 24ct",
                    "Welch's Fruit Snacks Mixed Fruit",
                    "Kellogg's Rice Krispies Treats Crispy Marshmallow Squares",
                    "Cheez-It Original/White Cheddar/Cheddar Jack Baked",
                    "Kellogg's Rice Krispies Treats Crispy Marshmallow Square ",
                    "Nabisco Original Premium Saltine Crackers",
                    "Betty Crocker® Fruit by the Foot®/Fruit Roll-Ups®",
                    "Nabisco Chips Ahoy! Original Chocolate Chip Cookies, 13 oz",
                    "Slim Jim Original Smoked Snack Sticks, 0.28 oz, 26 ct",
                    "Austin® Variety Pack™ Crackers 8-1.38 oz.",
                    "Snack Pack Vanilla/Chocolate Pudding Cups, 3.25 oz, 12 count",
                    "Lays Classic Mix 20 pk, 20 oz",
                    "Mott's® Medleys Assorted Fruit Flavored Snacks 24-0.8 oz. Pouches",
                    "Nabisco Ritz Crackers, 20.6 oz",
                    "Planters Honey Roasted Peanuts, 1 oz, 10 coun",
                    "Quaker Caramel Corn Rice Cakes, 6.56 oz",
                    "Del Monte No Sugar Added Variety Fruit Cups, 12 ct",
                    "Nabisco Oreo Chocolate Sandwich Cookies, 19.1 oz",
                    "Great Value Low Fat Pretzel Tiny Twists, 20 oz",
                    "Pringles Potato Crisps Chips Variety Pack, 27 count, 19.19 oz",
                    "Royal Dansk Danish Butter Cookies, 12 ounce tin",
                    "Quaker Chewy Chocolate Chip Granola Bars, 0.84 oz, 24 count",
                    "Lay's Flavor Mix Variety Pack, 1 oz, 20 count",
                    "UTZ Cheese Balls, 28 oz",
                    "Great Value Chocolate Chunk Chewy Granola Bars Variety Pack, 0.84 oz, 24 ct",
                    "Nutella: Hazelnut With Skim Milk & Cocoa Spread, 26.5 oz",
                    "Nabisco Newtons Fig Cookies, 2 oz, 12 count",
                    "Nutella: Hazelnut With Skim Milk Cocoa Spread, 13 Oz",
                    "Nature Valley® Oats 'n Honey Crunchy Granola Bars 18-2 ct Pouches",
                    "Great Value Vanilla Wafers, 11 oz",
                    "Pop Weaver Extra Butter Microwave Popcorn, 24ct"
            )
    );

    List<String> productPrice = new ArrayList<>(
            Arrays.asList(
                    "4.18",
                    "4.20",
                    "9.38",
                    "2.08",
                    "4.10",
                    "2.30",
                    "5.23",
                    "2.08",
                    "2.90",
                    "6.89",
                    "4.14",
                    "3.69",
                    "2.98",
                    "2.35",
                    "6.55",
                    "3.57",
                    "2.00",
                    "8.38",
                    "3.65",
                    "5.20",
                    "6.28",
                    "6.28",
                    "3.98",
                    "5.22",
                    "4.98",
                    "3.48",
                    "7.33",
                    "2.28",
                    "5.25",
                    "4.18",
                    "4.20",
                    "9.38",
                    "2.08",
                    "4.10",
                    "2.30",
                    "5.23",
                    "2.08",
                    "2.90",
                    "6.89",
                    "4.14",
                    "3.69",
                    "2.98",
                    "2.35",
                    "6.55",
                    "3.57",
                    "2.00",
                    "8.38",
                    "3.65",
                    "5.20",
                    "6.28",
                    "6.28",
                    "3.98",
                    "5.22",
                    "4.98",
                    "3.48",
                    "7.33",
                    "2.28",
                    "5.25",
                    "4.18",
                    "4.20"
            )
    );

    List<Integer> productRating = new ArrayList<>(
            Arrays.asList(
                    5,
                    4,
                    5,
                    3,
                    5,
                    4,
                    5,
                    5,
                    5,
                    4,
                    4,
                    5,
                    3,
                    5,
                    4,
                    3,
                    5,
                    2,
                    4,
                    3,
                    5,
                    5,
                    2,
                    5,
                    1,
                    6,
                    0,
                    3,
                    5,
                    5,
                    5,
                    5,
                    4,
                    5,
                    3,
                    5,
                    4,
                    5,
                    5,
                    5,
                    4,
                    4,
                    5,
                    3,
                    5,
                    4,
                    3,
                    5,
                    2,
                    4,
                    3,
                    5,
                    5,
                    2,
                    5,
                    1,
                    6,
                    0,
                    3,
                    5
            )
    );

    List<String> productImages = new ArrayList<>(
            Arrays.asList(
                    "image 1",
                    "image 2",
                    "image 3",
                    "image 4",
                    "image 5",
                    "image 6",
                    "image 7",
                    "image 8",
                    "image 9",
                    "image 10",
                    "image 1",
                    "image 2",
                    "image 3",
                    "image 4",
                    "image 5",
                    "image 6",
                    "image 7",
                    "image 8",
                    "image 9",
                    "image 10",
                    "image 1",
                    "image 2",
                    "image 3",
                    "image 4",
                    "image 5",
                    "image 6",
                    "image 7",
                    "image 8",
                    "image 9",
                    "image 10",
                    "image 1",
                    "image 2",
                    "image 3",
                    "image 4",
                    "image 5",
                    "image 6",
                    "image 7",
                    "image 8",
                    "image 9",
                    "image 10",
                    "image 1",
                    "image 2",
                    "image 3",
                    "image 4",
                    "image 5",
                    "image 6",
                    "image 7",
                    "image 8",
                    "image 9",
                    "image 10",
                    "image 1",
                    "image 2",
                    "image 3",
                    "image 4",
                    "image 5",
                    "image 6",
                    "image 7",
                    "image 8",
                    "image 9",
                    "image 10"
            )
    );
}
